version: "3.8"
services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  frontend:
    build:
      context: ./frontend
      target: dev
    command: ng serve --host 0.0.0.0 --port 4200
    volumes:
      - ./frontend:/src
    ports:
      - "4200:4200"